export enum ICON_NAMES {
  arrowUp = 'arrow-up',
  arrowDown = 'arrow-down',
  arrowLeft = 'arrow-left',
  arrowRight = 'arrow-right',
  arrowUpFilled = 'arrow-up-filled',
  arrowDownFilled = 'arrow-down-filled',
  arrowLeftFilled = 'arrow-left-filled',
  arrowRightFilled = 'arrow-right-filled',
  menu = 'menu',
  close = 'close',
  user = 'user',
  link = 'link',
  check = 'check',
  error = 'error',
  cry = 'cry',
}
