/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Swapica } from "./Swapica";
export * as factories from "./factories";
export { Erc20__factory } from "./factories/Erc20__factory";
export { Swapica__factory } from "./factories/Swapica__factory";
